name: text_recognition_new
description: "Smart Gym & Health Tracker - A Flutter application with OCR capabilities for medical reports"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase Core - Required for all Firebase services
  firebase_core: ^2.24.2
  
  # Firebase services (using compatible versions)
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6

  # Charts and Data Visualization
  fl_chart: ^0.65.0
  
  # Image handling
  image_picker: ^1.1.2

  # OCR Dependencies - FIXED COMPATIBLE VERSIONS
  google_mlkit_text_recognition: ^0.13.1
  google_mlkit_commons: ^0.8.1

  # UI dependencies
  cupertino_icons: ^1.0.8

  # Additional dependencies for health tracking
  http: ^1.1.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets for future use
  # assets:
  #   - assets/images/
  #   - assets/icons/