name: fitgen
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.5
  camera: ^0.10.5
  tflite_flutter: ^0.9.0
  image: ^4.0.17
  path_provider: ^2.0.15
  flutter_blue: ^0.8.0
  provider: ^6.0.5
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0 


flutter:
  uses-material-design: true
  
  # Add this assets section
  assets:
    - assets/images/
