name: fitgen
description: "AI Smart Fitness Companion with pose detection"
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  
  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.6.5
  
  # Camera and ML Kit (Stable versions)
  camera: ^0.10.5
  google_mlkit_pose_detection: 0.12.1
  google_mlkit_commons: ^0.8.1
  
  # Image processing
  image: ^4.0.17
  
  # Storage and utilities
  path_provider: ^2.1.1
  provider: ^6.1.1
  intl: ^0.19.0
  shared_preferences: ^2.5.3
  
  # Bluetooth (for wearables - optional)
  flutter_blue_plus: ^1.35.3
  
  # Web camera support
  camera_web: ^0.3.5
  
  # Text-to-speech for voice coaching
  flutter_tts: ^3.8.5
  
  # Permissions
  permission_handler: ^11.0.0
  image_picker: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/