// GENERATED FILE (stub)
// Replace the placeholder values below with the real values generated by
// the FlutterFire CLI (`flutterfire configure`) or paste values from your
// `google-services.json` for the Gym Firebase project.
//
// Example: run `flutterfire configure --project <your-gym-project-id>` to
// generate a proper `firebase_options.dart` and copy the Android options here
// as `DefaultFirebaseOptionsGym`.

import 'package:firebase_core/firebase_core.dart';

const FirebaseOptions DefaultFirebaseOptionsGym = FirebaseOptions(
  apiKey: 'REPLACE_WITH_GYM_API_KEY',
  appId: 'REPLACE_WITH_GYM_APP_ID',
  messagingSenderId: 'REPLACE_WITH_GYM_MESSAGING_SENDER_ID',
  projectId: 'REPLACE_WITH_GYM_PROJECT_ID',
  storageBucket: 'REPLACE_WITH_GYM_STORAGE_BUCKET',
  // If you use web, also supply authDomain and measurementId here.
);
