// GENERATED FILE (stub)
// Replace the placeholder values below with the real values generated by
// the FlutterFire CLI (`flutterfire configure`) or paste values from your
// `google-services.json` for the Medical Firebase project.
//
// Example: run `flutterfire configure --project <your-medical-project-id>` to
// generate a proper `firebase_options.dart` and copy the Android options here
// as `DefaultFirebaseOptionsMedical`.

import 'package:firebase_core/firebase_core.dart';

const FirebaseOptions DefaultFirebaseOptionsMedical = FirebaseOptions(
  apiKey: 'REPLACE_WITH_MEDICAL_API_KEY',
  appId: 'REPLACE_WITH_MEDICAL_APP_ID',
  messagingSenderId: 'REPLACE_WITH_MEDICAL_MESSAGING_SENDER_ID',
  projectId: 'REPLACE_WITH_MEDICAL_PROJECT_ID',
  storageBucket: 'REPLACE_WITH_MEDICAL_STORAGE_BUCKET',
  // If you use web, also supply authDomain and measurementId here.
);
