// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyv_uk99nI5VlJ-BImTb_NvfNcmhox6fA',
    appId: '1:374430418123:web:def7ff0656b0771fda874e',
    messagingSenderId: '374430418123',
    projectId: 'crudapp-35a42',
    authDomain: 'crudapp-35a42.firebaseapp.com',
    storageBucket: 'crudapp-35a42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPteuQXgJZScp7neoYN6AAYr19V4czVWs',
    appId: '1:374430418123:android:3ab60007e48537ccda874e',
    messagingSenderId: '374430418123',
    projectId: 'crudapp-35a42',
    storageBucket: 'crudapp-35a42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDAtiojQQtgnF9MhM0OQeSbt4ZvrAwnJQ',
    appId: '1:374430418123:ios:3ee70d2b6543ef93da874e',
    messagingSenderId: '374430418123',
    projectId: 'crudapp-35a42',
    storageBucket: 'crudapp-35a42.firebasestorage.app',
    iosBundleId: 'com.example.medicalGuidanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDAtiojQQtgnF9MhM0OQeSbt4ZvrAwnJQ',
    appId: '1:374430418123:ios:3ee70d2b6543ef93da874e',
    messagingSenderId: '374430418123',
    projectId: 'crudapp-35a42',
    storageBucket: 'crudapp-35a42.firebasestorage.app',
    iosBundleId: 'com.example.medicalGuidanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyv_uk99nI5VlJ-BImTb_NvfNcmhox6fA',
    appId: '1:374430418123:web:535680e80065d97eda874e',
    messagingSenderId: '374430418123',
    projectId: 'crudapp-35a42',
    authDomain: 'crudapp-35a42.firebaseapp.com',
    storageBucket: 'crudapp-35a42.firebasestorage.app',
  );
}
